# файл маршрутизации который контроллер nginx будет использовать для определения маршрута к нашим сервисам
apiVersion: networking.k8s.io/v1 # Указывает версию API, используемую для создания данного объекта Ingress.
kind: Ingress # Определяет тип объекта как Ingress. Ingress использовуется для управления доступом к службам и маршрутизации трафика на основе правил.
metadata: # Здесь вы можете указать метаданные для объекта Ingress, такие как имя и аннотации (опционально).
  name: ingress-srv
  annotations: # Здесь вы можете задать аннотации для Ingress, чтобы управлять его поведением.
    kubernetes.io/ingress.class: nginx # было kubernetes.io/ingress.class: |  Аннотация, определяющая класс Ingress, в данном случае, используется Ingress Nginx.
    nginx.ingress.kubernetes.io/use-regex: 'true' # Аннотация, указывающая, можно ли использовать регулярные выражения в правилах пути URL.
spec: # Описывает спецификации Ingress, включая правила маршрутизации.
  rules: # Определяет правила для маршрутизации трафика.
    - host: acme.com # Задает хост (доменное имя), для которого будут применяться следующие правила.
      http: # Описывает правила для HTTP-маршрутизации.
        paths: # Определяет пути URL и их настройки.
          - path: /api/platforms # Задает путь URL для доступа к службе platforms-clusterip-srv.
            pathType: Prefix # Определяет тип пути как префиксный матчинг.
            backend: # Определяет конечную точку (backend) для данного пути URL.
              service: # Определяет службу, на которую будет маршрутизироваться трафик.
                name: platforms-clusterip-srv # Задает имя службы, к которой будет направлен трафик.
                port: # Определяет порт службы.
                  number: 80 # Задает номер порта службы.
          - path: /api/c/platforms
            pathType: Prefix
            backend:
              service:
                name: commands-clusterip-srv
                port:
                  number: 80

              